version: '3.8'
services:
  app:
    build: 
      dockerfile: Dockerfile

    container_name: flask_app
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - Flask_network
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
networks:
  Flask_network:
    driver: bridge